/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int F(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int F_alloc_mem(void);
int F_init_mem(int mem);
void F_free_mem(int mem);
int F_checkout(void);
void F_release(int mem);
void F_incref(void);
void F_decref(void);
casadi_int F_n_in(void);
casadi_int F_n_out(void);
casadi_real F_default_in(casadi_int i);
const char* F_name_in(casadi_int i);
const char* F_name_out(casadi_int i);
const casadi_int* F_sparsity_in(casadi_int i);
const casadi_int* F_sparsity_out(casadi_int i);
int F_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int F_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define F_SZ_ARG 3
#define F_SZ_RES 2
#define F_SZ_IW 0
#define F_SZ_W 5
int G(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int G_alloc_mem(void);
int G_init_mem(int mem);
void G_free_mem(int mem);
int G_checkout(void);
void G_release(int mem);
void G_incref(void);
void G_decref(void);
casadi_int G_n_in(void);
casadi_int G_n_out(void);
casadi_real G_default_in(casadi_int i);
const char* G_name_in(casadi_int i);
const char* G_name_out(casadi_int i);
const casadi_int* G_sparsity_in(casadi_int i);
const casadi_int* G_sparsity_out(casadi_int i);
int G_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int G_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define G_SZ_ARG 3
#define G_SZ_RES 2
#define G_SZ_IW 0
#define G_SZ_W 4
int GradF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int GradF_alloc_mem(void);
int GradF_init_mem(int mem);
void GradF_free_mem(int mem);
int GradF_checkout(void);
void GradF_release(int mem);
void GradF_incref(void);
void GradF_decref(void);
casadi_int GradF_n_in(void);
casadi_int GradF_n_out(void);
casadi_real GradF_default_in(casadi_int i);
const char* GradF_name_in(casadi_int i);
const char* GradF_name_out(casadi_int i);
const casadi_int* GradF_sparsity_in(casadi_int i);
const casadi_int* GradF_sparsity_out(casadi_int i);
int GradF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int GradF_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define GradF_SZ_ARG 3
#define GradF_SZ_RES 2
#define GradF_SZ_IW 0
#define GradF_SZ_W 6
int JacG(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int JacG_alloc_mem(void);
int JacG_init_mem(int mem);
void JacG_free_mem(int mem);
int JacG_checkout(void);
void JacG_release(int mem);
void JacG_incref(void);
void JacG_decref(void);
casadi_int JacG_n_in(void);
casadi_int JacG_n_out(void);
casadi_real JacG_default_in(casadi_int i);
const char* JacG_name_in(casadi_int i);
const char* JacG_name_out(casadi_int i);
const casadi_int* JacG_sparsity_in(casadi_int i);
const casadi_int* JacG_sparsity_out(casadi_int i);
int JacG_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int JacG_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define JacG_SZ_ARG 3
#define JacG_SZ_RES 2
#define JacG_SZ_IW 0
#define JacG_SZ_W 3
int HessL(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int HessL_alloc_mem(void);
int HessL_init_mem(int mem);
void HessL_free_mem(int mem);
int HessL_checkout(void);
void HessL_release(int mem);
void HessL_incref(void);
void HessL_decref(void);
casadi_int HessL_n_in(void);
casadi_int HessL_n_out(void);
casadi_real HessL_default_in(casadi_int i);
const char* HessL_name_in(casadi_int i);
const char* HessL_name_out(casadi_int i);
const casadi_int* HessL_sparsity_in(casadi_int i);
const casadi_int* HessL_sparsity_out(casadi_int i);
int HessL_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int HessL_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define HessL_SZ_ARG 5
#define HessL_SZ_RES 2
#define HessL_SZ_IW 3
#define HessL_SZ_W 6
#ifdef __cplusplus
} /* extern "C" */
#endif
