/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) nlp_funcs_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {1, 2, 1};
static const casadi_int casadi_s3[7] = {2, 2, 0, 1, 2, 0, 1};

/* F:(x[2])->(f) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w0=w+0, w1, w2, w3;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 2, w0);
  /* #1: @1 = @0[0] */
  for (rr=(&w1), cs=w0+0; cs!=w0+1; cs+=1) *rr++ = *cs;
  /* #2: @2 = 1 */
  w2 = 1.;
  /* #3: @1 = (@1-@2) */
  w1 -= w2;
  /* #4: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #5: @2 = @0[1] */
  for (rr=(&w2), cs=w0+1; cs!=w0+2; cs+=1) *rr++ = *cs;
  /* #6: @3 = 2 */
  w3 = 2.;
  /* #7: @2 = (@2-@3) */
  w2 -= w3;
  /* #8: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #9: @1 = (@1+@2) */
  w1 += w2;
  /* #10: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int F(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int F_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real F_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_out(casadi_int i) {
  switch (i) {
    case 0: return "f";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 5;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 5*sizeof(casadi_real);
  return 0;
}

/* G:(x[2])->(g) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w0=w+0, w1, w2;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 2, w0);
  /* #1: @1 = @0[0] */
  for (rr=(&w1), cs=w0+0; cs!=w0+1; cs+=1) *rr++ = *cs;
  /* #2: @2 = @0[1] */
  for (rr=(&w2), cs=w0+1; cs!=w0+2; cs+=1) *rr++ = *cs;
  /* #3: @1 = (@1+@2) */
  w1 += w2;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int G(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int G_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int G_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void G_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int G_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void G_release(int mem) {
}

CASADI_SYMBOL_EXPORT void G_incref(void) {
}

CASADI_SYMBOL_EXPORT void G_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int G_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int G_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real G_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* G_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* G_name_out(casadi_int i) {
  switch (i) {
    case 0: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* G_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* G_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int G_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

CASADI_SYMBOL_EXPORT int G_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 4*sizeof(casadi_real);
  return 0;
}

/* GradF:(x[2])->(grad_f[2]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w0=w+0, *w1=w+2, w2, w3;
  const casadi_real *cs;
  /* #0: @0 = zeros(2x1) */
  casadi_clear(w0, 2);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 2, w1);
  /* #2: @2 = @1[1] */
  for (rr=(&w2), cs=w1+1; cs!=w1+2; cs+=1) *rr++ = *cs;
  /* #3: @3 = 2 */
  w3 = 2.;
  /* #4: @2 = (@2-@3) */
  w2 -= w3;
  /* #5: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #6: (@0[1] += @2) */
  for (rr=w0+1, cs=(&w2); rr!=w0+2; rr+=1) *rr += *cs++;
  /* #7: @2 = @1[0] */
  for (rr=(&w2), cs=w1+0; cs!=w1+1; cs+=1) *rr++ = *cs;
  /* #8: @3 = 1 */
  w3 = 1.;
  /* #9: @2 = (@2-@3) */
  w2 -= w3;
  /* #10: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #11: (@0[0] += @2) */
  for (rr=w0+0, cs=(&w2); rr!=w0+1; rr+=1) *rr += *cs++;
  /* #12: output[0][0] = @0 */
  casadi_copy(w0, 2, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int GradF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GradF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GradF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GradF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GradF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GradF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GradF_incref(void) {
}

CASADI_SYMBOL_EXPORT void GradF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GradF_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int GradF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real GradF_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GradF_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GradF_name_out(casadi_int i) {
  switch (i) {
    case 0: return "grad_f";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GradF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GradF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GradF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}

CASADI_SYMBOL_EXPORT int GradF_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 6*sizeof(casadi_real);
  return 0;
}

/* JacG:(x[2])->(jac_g[1x2]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w0=w+0, w1;
  const casadi_real *cs;
  /* #0: @0 = zeros(2x1) */
  casadi_clear(w0, 2);
  /* #1: @1 = 1 */
  w1 = 1.;
  /* #2: (@0[0] = @1) */
  for (rr=w0+0, cs=(&w1); rr!=w0+1; rr+=1) *rr = *cs++;
  /* #3: @1 = 1 */
  w1 = 1.;
  /* #4: (@0[1] = @1) */
  for (rr=w0+1, cs=(&w1); rr!=w0+2; rr+=1) *rr = *cs++;
  /* #5: output[0][0] = @0 */
  casadi_copy(w0, 2, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int JacG(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int JacG_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int JacG_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void JacG_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int JacG_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void JacG_release(int mem) {
}

CASADI_SYMBOL_EXPORT void JacG_incref(void) {
}

CASADI_SYMBOL_EXPORT void JacG_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int JacG_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int JacG_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real JacG_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JacG_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JacG_name_out(casadi_int i) {
  switch (i) {
    case 0: return "jac_g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* JacG_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* JacG_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int JacG_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 3;
  return 0;
}

CASADI_SYMBOL_EXPORT int JacG_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 3*sizeof(casadi_real);
  return 0;
}

/* HessL:(x[2],lam,sigma)->(hess_L[2x2,2nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w0=w+0, *w1=w+2, w2, w3;
  const casadi_real *cs;
  /* #0: @0 = zeros(2x2,2nz) */
  casadi_clear(w0, 2);
  /* #1: @1 = zeros(2x1) */
  casadi_clear(w1, 2);
  /* #2: @2 = input[2][0] */
  w2 = arg[2] ? arg[2][0] : 0;
  /* #3: @3 = (2.*@2) */
  w3 = (2.* w2 );
  /* #4: (@1[1] += @3) */
  for (rr=w1+1, cs=(&w3); rr!=w1+2; rr+=1) *rr += *cs++;
  /* #5: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #6: (@1[0] += @2) */
  for (rr=w1+0, cs=(&w2); rr!=w1+1; rr+=1) *rr += *cs++;
  /* #7: (@0[:2] = @1) */
  for (rr=w0+0, cs=w1; rr!=w0+2; rr+=1) *rr = *cs++;
  /* #8: (@0[:2] = @1) */
  for (rr=w0+0, cs=w1; rr!=w0+2; rr+=1) *rr = *cs++;
  /* #9: @1 = @0' */
  casadi_trans(w0,casadi_s3, w1, casadi_s3, iw);
  /* #10: output[0][0] = @1 */
  casadi_copy(w1, 2, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int HessL(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int HessL_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int HessL_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void HessL_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int HessL_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void HessL_release(int mem) {
}

CASADI_SYMBOL_EXPORT void HessL_incref(void) {
}

CASADI_SYMBOL_EXPORT void HessL_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int HessL_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int HessL_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real HessL_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* HessL_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "lam";
    case 2: return "sigma";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* HessL_name_out(casadi_int i) {
  switch (i) {
    case 0: return "hess_L";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* HessL_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* HessL_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int HessL_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 6;
  return 0;
}

CASADI_SYMBOL_EXPORT int HessL_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 6*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
